In [1]:
#数组属性
import numpy as np

numbers=np.array([1,2,3,4])

print(numbers)
print(type(numbers))
print("维数: ",numbers.ndim)
print("形状：",numbers.shape)
print("元素数量: ",numbers.size)
print("数据类型: ",numbers.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
维数:  1
形状： (4,)
元素数量:  4
数据类型:  int64


In [2]:
#二维数组
matrix=np.array([
    [1,2,3],
    [4,5,6]
])

print(matrix)
print(type(matrix))
print("维数: ",matrix.ndim)
print("形状：",matrix.shape)
print("元素数量: ",matrix.size)
print("数据类型: ",matrix.dtype)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
维数:  2
形状： (2, 3)
元素数量:  6
数据类型:  int64


In [3]:
#二维切片
print("第一行: ",matrix[0])
print("第二列: ",matrix[:,1])
print("第一行后两列: ",matrix[0,1:3])
print("所有行的后两列: ",matrix[:,1:3])

第一行:  [1 2 3]
第二列:  [2 5]
第一行后两列:  [2 3]
所有行的后两列:  [[2 3]
 [5 6]]


In [4]:
#创建和改变形状
a=np.zeros((2,3))       # 两行三列，全是 0
b=np.ones((2,3))        # 两行三列，全是 1
c=np.arange(0,10,2)     # 类似 range：0、2、4、6、8
d=np.linspace(0,1,5)        #在 0 到 1 之间均匀取 5 个数

print(a,b,c,d)
print("\n")

#改变形状
numbers=np.arange(1,13)
matrix=numbers.reshape(3,4)

print(numbers)
print("\n")
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]] [[1. 1. 1.]
 [1. 1. 1.]] [0 2 4 6 8] [0.   0.25 0.5  0.75 1.  ]


[ 1  2  3  4  5  6  7  8  9 10 11 12]


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
#向量化运算
x=np.array([1,2,3,4])

print(x+10)
print(x*2)
print(x**2)
print(x>2)

a=np.array([1,2,3])
b=np.array([4,5,6])

print(a*b)

[11 12 13 14]
[2 4 6 8]
[ 1  4  9 16]
[False False  True  True]
[ 4 10 18]


In [6]:
nums=np.arange(1,13)
matrix=nums.reshape(3,4).copy()
print(matrix.ndim)
print(matrix.shape)
print(matrix.size)
print(matrix.dtype)
print(matrix[1])
print(matrix[:,2])
print(matrix[-2:,-2:])
matrix*=10
print(matrix)
print(nums)

2
(3, 4)
12
int64
[5 6 7 8]
[ 3  7 11]
[[ 7  8]
 [11 12]]
[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [7]:
#布尔索引
scores=np.array([85, 92, 58, 78, 95, 60])
mask=scores>=90
print(mask)
print(scores[mask])

selected=scores[(scores>=60)&(scores<=90)]
print(selected)

adjusted_scores=scores.copy()
adjusted_scores[adjusted_scores<60]=60
print(scores)
print(adjusted_scores)

#二维数组
matrix=np.arange(1,13).reshape(3,4)
print(matrix[matrix>6])     #这种写法会把满足条件的元素取出来组成一个一维数组，不再保持原来的二维形状。

[False  True False False  True False]
[92 95]
[85 78 60]
[85 92 58 78 95 60]
[85 92 60 78 95 60]
[ 7  8  9 10 11 12]


In [8]:
#花式索引
#花式索引可以使用一个整数列表，同时指定多个位置
matrix=np.arange(1,13).reshape(3,4)
print(matrix)
print("第1，3行：")
print(matrix[[0,2]])
print("第1，3列：")
print(matrix[:,[0,2]])
print("\n")
print(matrix[[0, 2], [1, 3]])
print("\n")
rows = [0, 2]
columns = [1, 3]
print(matrix[np.ix_(rows, columns)])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
第1，3行：
[[ 1  2  3  4]
 [ 9 10 11 12]]
第1，3列：
[[ 1  3]
 [ 5  7]
 [ 9 11]]


[ 2 12]


[[ 2  4]
 [10 12]]


In [9]:
#单个索引与切片的维度区别
matrix = np.arange(1, 13).reshape(3, 4)
row1=matrix[0]
row2=matrix[0:1]
print(row1)
print(row1.shape)
print(row2)
print(row2.shape)
#matrix[0]：使用单个整数选择一行，这个行维度被消掉。
#matrix[0:1]：使用切片选择一行，仍然保留二维结构。

[1 2 3 4]
(4,)
[[1 2 3 4]]
(1, 4)


In [10]:
scores = np.array([85, 92, 58, 78, 95, 60])
matrix = np.arange(1, 13).reshape(3, 4)
print(scores[scores>=80])
print(scores[(scores>=60)&(scores<=90)])
cp_scores=scores.copy()
cp_scores[cp_scores<60]=60
print(cp_scores)
print(matrix[[0,2]])
print(matrix[:,[1,3]])
print(matrix[[0,2],[1,3]])
print(matrix[np.ix_([0,2],[1,3])])
print(matrix[0].shape)
print(matrix[0:1].shape)

[85 92 95]
[85 78 60]
[85 92 60 78 95 60]
[[ 1  2  3  4]
 [ 9 10 11 12]]
[[ 2  4]
 [ 6  8]
 [10 12]]
[ 2 12]
[[ 2  4]
 [10 12]]
(4,)
(1, 4)


In [11]:
#创建数组时指定类型
integers=np.array([1,2,3],dtype=np.int32)
floats=np.array([1,2,3],dtype=np.float32)
pixels=np.array([0,128,255],dtype=np.uint8)
print(integers,integers.dtype)
print(floats, floats.dtype)
print(pixels, pixels.dtype)

#astype() 类型转换
#astype()通常返回一个新数组，不修改原数组
scores=np.array([89.9,76.4,92.8])
integer_scores=scores.astype(np.int32)
print(scores)
print(integer_scores)
print(scores.dtype)
print(integer_scores.dtype)

#先四舍五入
rounded_scores=np.round(scores).astype(np.int32)
print(rounded_scores)

[1 2 3] int32
[1. 2. 3.] float32
[  0 128 255] uint8
[89.9 76.4 92.8]
[89 76 92]
float64
int32
[90 76 93]


In [12]:
#神经网络通常使用 float32，而且经常把像素缩放到 0～1
pixels = np.array([
    [0, 64, 128],
    [192, 224, 255]
], dtype=np.uint8)
normalized_pixels=pixels.astype(np.float32)/255.0
print(pixels)
print(pixels.dtype)
print(normalized_pixels)
print(normalized_pixels.dtype)

#reshape() 中的 -1
#如果只想指定一个维度，另一个维度让 NumPy 自动计算，可以使用 -1
numbers=np.arange(1,13)
a=numbers.reshape(3,-1)
b=numbers.reshape(-1,6)
print(a)
print(a.shape)
print(b)
print(b.shape)

#flatten() 与 ravel(),把多维数组变成一维
#flatten()：一定复制
matrix=np.arange(1,7).reshape(2,3)
flattened=matrix.flatten()
flattened[0]=100
print(flattened)
print(matrix)

#ravel()：尽量返回视图,修改 raveled 会影响 matrix,二者共享数据
matrix=np.arange(1,7).reshape(2,3)
raveled=matrix.ravel()
raveled[0]=100
print(raveled)
print(matrix)

[[  0  64 128]
 [192 224 255]]
uint8
[[0.        0.2509804 0.5019608]
 [0.7529412 0.8784314 1.       ]]
float32
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)
[100   2   3   4   5   6]
[[1 2 3]
 [4 5 6]]
[100   2   3   4   5   6]
[[100   2   3]
 [  4   5   6]]


In [13]:
#完整对比实验
#np.shares_memory(a, b) 用来判断两个 NumPy 数组是否共享同一块底层内存
matrix = np.arange(1, 7).reshape(2, 3)

flattened = matrix.flatten()
raveled = matrix.ravel()

print("flatten 是否共享内存：",
      np.shares_memory(matrix, flattened))

print("ravel 是否共享内存：",
      np.shares_memory(matrix, raveled))
flattened[0] = 100
raveled[1] = 200

print("flattened：", flattened)
print("raveled：", raveled)
print("matrix：")
print(matrix)

flatten 是否共享内存： False
ravel 是否共享内存： True
flattened： [100   2   3   4   5   6]
raveled： [  1 200   3   4   5   6]
matrix：
[[  1 200   3]
 [  4   5   6]]


In [14]:
nums=np.arange(12,dtype=np.uint8)
nums1=nums.reshape(3,4)
nums2=nums1.astype(np.float32)
nums3=nums2/11.0
flattened=nums3.flatten()
raveled=nums3.ravel()
print("flattened是否与nums3共享内存：",np.shares_memory(flattened,nums3))
print("raveled是否与nums3共享内存：",np.shares_memory(raveled,nums3))
flattened[0]=100
raveled[1]=200
print(nums3)
print(nums1.dtype,nums1.shape)
print(nums2.dtype,nums2.shape)
print(nums3.dtype,nums3.shape)

flattened是否与nums3共享内存： False
raveled是否与nums3共享内存： True
[[0.0000000e+00 2.0000000e+02 1.8181819e-01 2.7272728e-01]
 [3.6363637e-01 4.5454547e-01 5.4545456e-01 6.3636363e-01]
 [7.2727275e-01 8.1818181e-01 9.0909094e-01 1.0000000e+00]]
uint8 (3, 4)
float32 (3, 4)
float32 (3, 4)


In [15]:
# 7月19日：NumPy广播
# 广播基础
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

column_bonus = np.array([10, 20, 30])
row_bonus = np.array([100, 200])[:, None]

print("matrix shape:", matrix.shape)
print("column_bonus shape:", column_bonus.shape)
print("row_bonus shape:", row_bonus.shape)

print("每列增加不同数：")
print(matrix + column_bonus)

print("每行增加不同数：")
print(matrix + row_bonus)

print("同时增加：")
print(matrix + column_bonus + row_bonus)

# (2, 3) 与 (3,)        能
# (2, 3) 与 (2, 1)      能
# (2, 3) 与 (2,)        不能
# (3, 1) 与 (1, 4)      能

matrix shape: (2, 3)
column_bonus shape: (3,)
row_bonus shape: (2, 1)
每列增加不同数：
[[11 22 33]
 [14 25 36]]
每行增加不同数：
[[101 102 103]
 [204 205 206]]
同时增加：
[[111 122 133]
 [214 225 236]]


In [16]:
#应用一：成绩矩阵
# scores 的每一行代表一名学生。
# 每一列代表一门课程。
scores = np.array([
    [80, 90, 70],
    [60, 75, 85],
    [95, 88, 92]
])

course_bonus = np.array([5, 0, 10])

student_bonus = np.array([
    [1],
    [2],
    [3]
])

print("scores shape:", scores.shape)
print("course_bonus shape:", course_bonus.shape)
print("student_bonus shape:", student_bonus.shape)

print("按课程加分：")
print(scores + course_bonus)

print("按学生加分：")
print(scores + student_bonus)

print("同时加分：")
print(scores + course_bonus + student_bonus)

scores shape: (3, 3)
course_bonus shape: (3,)
student_bonus shape: (3, 1)
按课程加分：
[[ 85  90  80]
 [ 65  75  95]
 [100  88 102]]
按学生加分：
[[81 91 71]
 [62 77 87]
 [98 91 95]]
同时加分：
[[ 86  91  81]
 [ 67  77  97]
 [103  91 105]]


In [17]:
#应用二：RGB 通道广播
image = np.array([
    [[100, 150, 200], [50, 100, 150]],
    [[200, 120, 80], [0, 64, 255]]
], dtype=np.float32)        #2*2*3的RGB图片，三通道红绿蓝

channel_offset = np.array([10, 20, 30])

adjusted_image = image + channel_offset

print("image shape:", image.shape)
print("channel_offset shape:", channel_offset.shape)

print("原始第一个像素：")
print(image[0, 0])

print("调整后第一个像素：")
print(adjusted_image[0, 0])

print("调整后的完整图像：")
print(adjusted_image)

clipped_image = np.clip(adjusted_image, 0, 255)     #小于 min 的值改成 min，大于 max 的值改成 max
print(clipped_image)

image shape: (2, 2, 3)
channel_offset shape: (3,)
原始第一个像素：
[100. 150. 200.]
调整后第一个像素：
[110. 170. 230.]
调整后的完整图像：
[[[110. 170. 230.]
  [ 60. 120. 180.]]

 [[210. 140. 110.]
  [ 10.  84. 285.]]]
[[[110. 170. 230.]
  [ 60. 120. 180.]]

 [[210. 140. 110.]
  [ 10.  84. 255.]]]


In [18]:
#聚合练习
scores = np.array([
    [80, 90, 70],
    [60, 75, 85],
    [95, 88, 92]
])

#所有成绩总和和总平均分
print(scores.sum())
print(scores.mean())

#每门课程平均分
print(scores.mean(axis=0))

#每名学生平均分
print(scores.mean(axis=1))

#每门课程最高分和最低分
print(scores.max(axis=0),scores.min(axis=0))

#每名学生最高分
print(scores.max(axis=1))

#每门课程最高分所在的学生下标
print(scores.argmax(axis=0))

#每名学生最高分所在的课程下标
print(scores.argmax(axis=1))

#每门课程标准差
print(scores.std(axis=0))

#使用 keepdims=True 计算每名学生平均分
print(scores.mean(axis=1,keepdims=True))

#打印所有结果的 shape，说明哪个维度被消掉了
course_mean = scores.mean(axis=0)
student_mean = scores.mean(axis=1)
student_mean_keepdims = scores.mean(axis=1, keepdims=True)

print("每门课程平均分 shape：", course_mean.shape)
print("每名学生平均分 shape：", student_mean.shape)
print("保留维度后的平均分 shape：", student_mean_keepdims.shape)

#让每名学生的成绩减去自己的平均分，打印结果
ans=scores-scores.mean(axis=1,keepdims=True)
print(ans)

#验证处理后每一行的平均值接近 0
print(ans.mean(axis=1))

735
81.66666666666667
[78.33333333 84.33333333 82.33333333]
[80.         73.33333333 91.66666667]
[95 90 92] [60 75 70]
[90 85 95]
[2 0 2]
[1 2 0]
[14.33720878  6.64997911  9.1772666 ]
[[80.        ]
 [73.33333333]
 [91.66666667]]
每门课程平均分 shape： (3,)
每名学生平均分 shape： (3,)
保留维度后的平均分 shape： (3, 1)
[[  0.          10.         -10.        ]
 [-13.33333333   1.66666667  11.66666667]
 [  3.33333333  -3.66666667   0.33333333]]
[ 0.00000000e+00  4.73695157e-15 -4.73695157e-15]


In [19]:
#对每门课程进行 Z-score 标准化
scores = np.array([
    [80, 90, 70],
    [60, 75, 85],
    [95, 88, 92]
], dtype=np.float32)

course_mean = scores.mean(axis=0, keepdims=True)
course_std = scores.std(axis=0, keepdims=True)

standardized_scores = (scores - course_mean) / course_std

print("每门课程平均分：")
print(course_mean)
print("shape:", course_mean.shape)

print("每门课程标准差：")
print(course_std)
print("shape:", course_std.shape)

print("标准化后的成绩：")
print(standardized_scores)

print("标准化后每列平均值：")
print(standardized_scores.mean(axis=0))

print("标准化后每列标准差：")
print(standardized_scores.std(axis=0))

每门课程平均分：
[[78.333336 84.333336 82.333336]]
shape: (1, 3)
每门课程标准差：
[[14.337209  6.649979  9.177266]]
shape: (1, 3)
标准化后的成绩：
[[ 0.11624746  0.8521326  -1.3439009 ]
 [-1.2787242  -1.4035136   0.29057282]
 [ 1.1624762   0.5513798   1.0533272 ]]
标准化后每列平均值：
[-1.9868214e-07 -3.7749609e-07 -2.7815500e-07]
标准化后每列标准差：
[1. 1. 1.]


In [20]:
#Min-Max 缩放
course_min = scores.min(axis=0, keepdims=True)
course_max = scores.max(axis=0, keepdims=True)

scaled_scores = (
    (scores - course_min)
    / (course_max - course_min)
)

print("每列最小值：", course_min)
print("每列最大值：", course_max)

print("缩放后的成绩：")
print(scaled_scores)

print("缩放后每列最小值：")
print(scaled_scores.min(axis=0))

print("缩放后每列最大值：")
print(scaled_scores.max(axis=0))

每列最小值： [[60. 75. 70.]]
每列最大值： [[95. 90. 92.]]
缩放后的成绩：
[[0.5714286 1.        0.       ]
 [0.        0.        0.6818182]
 [1.        0.8666667 1.       ]]
缩放后每列最小值：
[0. 0. 0.]
缩放后每列最大值：
[1. 1. 1.]


In [21]:
# 常数列与除零保护
data = np.array([
    [10, 1],
    [20, 1],
    [30, 1]
], dtype=np.float32)

mean = data.mean(axis=0, keepdims=True)
std = data.std(axis=0, keepdims=True)

#np.where(条件, 条件成立时取什么, 条件不成立时取什么)
safe_std = np.where(std == 0, 1, std)
standardized = (data - mean) / safe_std

print("平均值：", mean)
print("原标准差：", std)
print("安全标准差：", safe_std)
print("标准化结果：")
print(standardized)

print("处理后每列平均值：")
print(standardized.mean(axis=0))

print("处理后每列标准差：")
print(standardized.std(axis=0))

#Min-Max保护
minimum = data.min(axis=0, keepdims=True)
maximum = data.max(axis=0, keepdims=True)

data_range = maximum - minimum
safe_range = np.where(data_range == 0, 1, data_range)

scaled = (data - minimum) / safe_range

print("安全极差：", safe_range)
print("Min-Max 结果：")
print(scaled)

平均值： [[20.  1.]]
原标准差： [[8.164966 0.      ]]
安全标准差： [[8.164966 1.      ]]
标准化结果：
[[-1.2247449  0.       ]
 [ 0.         0.       ]
 [ 1.2247449  0.       ]]
处理后每列平均值：
[0. 0.]
处理后每列标准差：
[1. 0.]
安全极差： [[20.  1.]]
Min-Max 结果：
[[0.  0. ]
 [0.5 0. ]
 [1.  0. ]]


In [22]:
#常用随机函数
rng = np.random.default_rng(seed=42)

integers = rng.integers(0, 10, size=5)
uniform_01 = rng.random(size=5)
uniform_range = rng.uniform(10, 20, size=5)
normal_data = rng.normal(loc=75, scale=10, size=5)

print("随机整数：", integers)
print("0～1 均匀分布：", uniform_01)
print("10～20 均匀分布：", uniform_range)
print("正态分布：", normal_data)        #均值为 75、标准差为 10 的正态分布

#同一个生成器连续调用
rng = np.random.default_rng(seed=42)

a = rng.integers(0, 100, size=5)
b = rng.integers(0, 100, size=5)

print(a)
print(b)

随机整数： [0 7 6 4 4]
0～1 均匀分布： [0.69736803 0.09417735 0.97562235 0.7611397  0.78606431]
10～20 均匀分布： [11.28113633 14.50385938 13.70798024 19.26764989 16.4386512 ]
正态分布： [86.27241207 79.67509342 66.40707537 78.68750784 65.41117399]
[ 8 77 65 43 43]
[85  8 69 20  9]


In [23]:
#验证相同种子
rng1 = np.random.default_rng(seed=2026)
rng2 = np.random.default_rng(seed=2026)

data1 = rng1.normal(loc=75, scale=10, size=10)
data2 = rng2.normal(loc=75, scale=10, size=10)

print(data1)
print(data2)
print("两个结果是否完全相同：")
print(np.array_equal(data1, data2))

#如果种子不同
rng3 = np.random.default_rng(seed=2027)
data3 = rng3.normal(loc=75, scale=10, size=10)

print(np.array_equal(data1, data3))

[67.06877525 77.40571284 56.0367365  88.9577171  81.38294741 72.07952515
 71.88050672 78.03835368 72.32339698 72.74091139]
[67.06877525 77.40571284 56.0367365  88.9577171  81.38294741 72.07952515
 71.88050672 78.03835368 72.32339698 72.74091139]
两个结果是否完全相同：
True
False


In [24]:
#完整统计练习
rng = np.random.default_rng(seed=2026)

course_means = np.array([78, 82, 75])
course_stds = np.array([10, 8, 12])

scores = rng.normal(        #正态分布
    loc=course_means,
    scale=course_stds,
    size=(100, 3)
)

scores = np.clip(scores, 0, 100)        #限制成绩的最值
scores = scores.astype(np.float32)

print("成绩矩阵形状：", scores.shape)
print("前 5 名学生：")
print(scores[:5])

print("每门课程平均分：")
print(scores.mean(axis=0))

print("每门课程标准差：")
print(scores.std(axis=0))

print("每门课程最低分：")
print(scores.min(axis=0))

print("每门课程最高分：")
print(scores.max(axis=0))

print("每门课程及格人数：")
print((scores >= 60).sum(axis=0))       #sum求和把True当作1累加

print("每门课程及格率：")
print((scores >= 60).mean(axis=0))

rng_again = np.random.default_rng(seed=2026)

scores_again = rng_again.normal(
    loc=course_means,
    scale=course_stds,
    size=(100, 3)
)

scores_again = np.clip(scores_again, 0, 100)
scores_again = scores_again.astype(np.float32)

print("相同种子能否复现：")
print(np.array_equal(scores, scores_again))

成绩矩阵形状： (100, 3)
前 5 名学生：
[[70.06878  83.92457  52.244083]
 [91.95772  87.10636  71.49543 ]
 [74.88051  84.43068  71.78808 ]
 [75.74091  87.760544 81.17646 ]
 [77.35872  81.316185 76.93099 ]]
每门课程平均分：
[78.72173 81.67512 77.03463]
每门课程标准差：
[ 9.880924  8.389759 12.459137]
每门课程最低分：
[55.119507 62.3202   30.031034]
每门课程最高分：
[100. 100. 100.]
每门课程及格人数：
[ 99 100  94]
每门课程及格率：
[0.99 1.   0.94]
相同种子能否复现：
True
